### ISSUE TITLE
Distributed Map Weather Analysis Pattern - Failed to access S3 assets

### ISSUE THREAD

**Issue by rohanmeh** [aws-samples/step-functions-workflows-collection#101]
**Describe the bug**

CloudFormation deployment, resource: TemperaturesFunction

Resource handler returned message: "Your access has been denied by S3, please make sure your request credentials have permission to GetObject for da-public-assets/workflows/distributed-map-weather-anaysis/f31f19db9b706335c454fc213e75a5e6. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: Lambda, Status Code: 403, Request ID: 886daa8a-21ec-486b-ad77-558a069be5f5)" (RequestToken: 76ab2d83-c9bb-3a96-c24c-2baf621d2ca3, HandlerErrorCode: AccessDenied)
--

<br class="Apple-interchange-newline">
**To Reproduce**
1. Deploy CloudFormation stack for https://serverlessland.com/workflows/distributed-map-weather-anaysis
2. See error in stack deployment logs.

**Expected behavior**
Stack deployed successfully.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shinglyu** [comment]
I saw the same error for other workflows, for example https://serverlessland.com/workflows/call-http-api and https://serverlessland.com/workflows/batch-lambda-sam
Also the S3 bucket is only available in us-east-1, which is not very obvious on the page.
