### ISSUE TITLE
New workflow submission

### ISSUE THREAD

**Issue by StefanAppel** [aws-samples/step-functions-workflows-collection#107]
This issue is for pull request #106  

Please include the event-driven-workflow-monitor example in the repo. It's CDK-based and deploys a sample workflow, a DynamoDB table, an EventBridge event bus and Lambda functions to showcase the integration of "external" events with workflows.

Below information is also included in the example-workflow.json. Further details are available in the Readme.

Thanks,
Stefan

---
- Description:
This example demonstrates how AWS Step Functions workflows can integrate with events in an event-driven architecture. The example implements a workflow monitor task to react to events sent to Amazon EventBridge. For that, the monitor task stores workflow metadata in a DynamoDB table. Events sent to EventBridge trigger Lambda functions, which send fail or success commands back to the workflow monitor task."

- Simplicity:
2 -  Pattern

- Diagram:
https://github.com/StefanAppel/step-functions-workflows-collection/blob/StefanAppel-feature-event-driven-workflow-monitor/event-driven-workflow-monitor/resources/statemachine.png

- Type: Must be one of (`Standard`, `Express`):
Standard

Resources should link to AWS documentation and AWS blogs related to the post (1-5 maximum):
Building event-driven architectures on AWS
https://catalog.us-east-1.prod.workshops.aws/workshops/63320e83-6abc-493d-83d8-f822584fb3cb/en-US

Framework: currently, we support SAM or CDK.
CDK

Author bio:
Stefan is a Senior Solutions Architect at AWS. He supports global companies adopt cloud technologies.
https://www.linkedin.com/in/appel-stefan/

You must ensure that the sections of the model README.md are completed in full.
Done.

**Comment by bls20AWS** [comment]
Merged, this will go live on serverlessland today at: https://serverlessland.com/workflows/Event-driven-Workflow-Monitor
