### ISSUE TITLE
AWS Step Functions Progress Tracking via WebSocket API

### ISSUE THREAD

**Issue by alparamonov** [aws-samples/step-functions-workflows-collection#111]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

Note the following information for the model:

- Description (intro.text):
  ```
   This project creates an AWS Step Functions, which mocks a mutli-step ordering process, and demonstrates how clients can monitor the progress via Amazon API Gateway Websocket.
   The project demonstrates how to report the progress via AWS SDK integrations and via AWS Lambda.
  ```
- Simplicity: `2 -  Pattern`
- Diagram: ✅
- Type: `Standard`
- Resources should link to AWS documentation and AWS blogs related to the post (1-5 maximum):
  ```
   1. Repository https://github.com/aws-samples/aws-step-functions-progress-tracking
   2. Blog post is on the way
   ```
- Framework: SAM
- Authors: [Alex Paramonov](https://www.linkedin.com/in/alexey-paramonov/) and [Maximilian Schellhorn](https://www.linkedin.com/in/maximilian-schellhorn-46020b162/)

You must ensure that the sections of the model README.md are completed in full: ✅

**Comment by bls20AWS** [comment]
Please make a PR with a completed https://github.com/aws-samples/step-functions-workflows-collection/blob/main/_workflow_model/example-workflow.json and a clean .png of the step functions graph (just the workflow, without peripheral resources)
