### ISSUE TITLE
pagination-loop: possible for incomplete execution output

### ISSUE THREAD

**Issue by deric4** [aws-samples/step-functions-workflows-collection#13]
Hi!  I just finished watching this serverlessland office hours: https://www.youtube.com/watch?v=jRuIrsjJePg with @julianwood and @bls20AWS (more plz 😄 ) and noticed what looked like a step function definition that could return  incomplete(?)/incorrect(?) results:

When the condition for entering `List Executions nextPage` state is met, the `ResultPath` will _override_ the value at `$.executions` in the Execution Output rather than append to it, effectively returning just the executions from the last API request instead of _all_ executions that matched the status filter.
https://github.com/aws-samples/step-functions-workflows-collection/blob/17351467a5014218d869b9160de34b21f5f87be1/pagination-loop/statemachine/statemachine.asl.json#L15-L24

I don't have a step function that has enough history deployed in my test account to trigger the pagination but hopefully this definition is enough to reproduce/show:

```jsonc
{
  "Comment": "A description of my state machine",
  "StartAt": "state-1",
  "States": {
    "state-1": {
      "Type": "Pass",
      "InputPath": "$$.State..Name", // using '..' to return an array: ["state-1"]
      "ResultPath": "$.output",
      "Next": "state-2"
    },
    "state-2": {
      "Type": "Pass",
      "InputPath": "$$.State..Name",
      "End": true,
      "ResultPath": "$.output"
    }
  }
}
```
### expected execution output

_assuming the example sfn def is a correct simplification of `pagination-loop`_
```json
{
  "Comment": "Insert your JSON here",
  "output": [
    "state-1",
    "state-2"
  ]
}
```

### actual execution input
❌ 
```json
{
  "Comment": "Insert your JSON here",
  "output": [
    "state-2"
  ]
}
```
---
### execution input
<img width="530" alt="execution-input" src="https://user-images.githubusercontent.com/5762138/179860187-98a03da2-9434-42a1-a30b-98cda6922022.png">

### execution output
<img width="555" alt="execution-output" src="https://user-images.githubusercontent.com/5762138/179860331-ba91a093-a50e-4d78-907a-83c43496e6c0.png">

### state-2-input
<img width="889" alt="state-2-input" src="https://user-images.githubusercontent.com/5762138/179860849-44e27c9c-4de1-45c1-aec6-0f3b19e3ce91.png">

### state-2-output
<img width="815" alt="state-2-output" src="https://user-images.githubusercontent.com/5762138/179860688-24f1fa7e-8476-4167-9355-d7c375f929e3.png">

**Comment by bls20AWS** [comment]
Hello @deric4, thanks for raising this issue. The original requirement of this workflow was to get to the last execution in the list. I think what you propose here is a good an improvement, though, (until the payload limit is reached). I'm going to add your suggestion to the ASL.  Thanks again for submitting this,
