### ISSUE TITLE
New workflow submission - TTS Converter pattern using CDK with Python

### ISSUE THREAD

**Issue by adrianjhunter** [aws-samples/step-functions-workflows-collection#139]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

Note the following information for the workflow:

- Name: TTS Converter
- Description: This workflow takes text files uploaded to Amazon S3 and uses Amazon Polly to synthesis the text to speech. The audio file is saved to Amazon S3.
- Simplicity: 3 - Application
- Diagram: Included
- Type: Standard
- Resources should link to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: CDK
- Language: Python
- PR: #138
- Original Author of workflow: [Yoonseo Kim](https://www.linkedin.com/in/yoonseo-kim-573780208/)
- CDK Author: [Adrian Hunter](https://www.linkedin.com/in/adrianhunter/)

You must ensure that the sections of the model README.md are completed in full.

**Comment by bls20AWS** [comment]
Thank you for submitting
