### ISSUE TITLE
New workflow submission - Word Filtering Script Generator pattern using CDK with Python

### ISSUE THREAD

**Issue by adrianjhunter** [aws-samples/step-functions-workflows-collection#141]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

Note the following information for the workflow:

- Name: Word Filtering Script Generator
- Description: This workflow generates scripts that filters certain words from video or audio using Amazon Transcribe.
- Simplicity: 3 - Application
- Diagram: Included
- Type: Standard
- Resources should link to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: CDK
- Language: Python
- PR: #140
- Original Author of workflow: [Yoonseo Kim](https://www.linkedin.com/in/yoonseo-kim-573780208/)
- CDK Author: [Adrian Hunter](https://www.linkedin.com/in/adrianhunter/)

You must ensure that the sections of the model README.md are completed in full.

**Comment by bls20AWS** [comment]
thanks for submitting
