### ISSUE TITLE
New workflow submission - Support Notifications workflow using CDK with Python

### ISSUE THREAD

**Issue by adrianjhunter** [aws-samples/step-functions-workflows-collection#143]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

Note the following information for the workflow:

- Name: Support Notifications
- Description: For customers with many administrators who may be logging support cases, a manager may be interested when business critical or production systems are down. Rather than relying on the administrator to add the manager to the case, this workflow sends an email notification via Amazon SNS to the manager notifying them of newly created urgent or critical cases. The manager can then choose to login to the AWS Console, review the case and add themselves as an additional contact if they wish to receive further case updates.
- Simplicity: 3 - Application
- Diagram: Included
- Type: Standard
- Resources should link to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: CDK
- Language: Python
- PR: #142
- Author: [Adrian Hunter](https://www.linkedin.com/in/adrianhunter/)

You must ensure that the sections of the model README.md are completed in full.

**Comment by bls20AWS** [comment]
Cool workflow! Thanks for submitting,
