### ISSUE TITLE
New workflow submission - Chain of Responsibility pattern added Python and Typescript CDK

### ISSUE THREAD

**Issue by fanhongy** [aws-samples/step-functions-workflows-collection#147]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

Note the following information for the model:

* Name: chain-of-responsibility
* Description: The AWS Step Functions Workflow is used to demonstrate how an ATM would be dispensing different types of bills until the entire requested amount is dispensed.
You must ensure that the sections of the model README.md are completed in full.
* Simplicity: 2 - Patterns
* Diagram: Included
* Type: Standard
* Resources should link to AWS documentation and AWS blogs related to the post (1-5 maximum).
* Framework: CDK
* Language Python, Typescript
* PR: #146 
* Original Author of workflow: [Tsvetko Tsenkov](https://www.linkedin.com/in/tsvetko-tsenkov-6501413/)
* CDK Author: [Stan Fan](https://www.linkedin.com/in/hongyi-fan-05101992/)

You must ensure that the sections of the model README.md are completed in full.

**Comment by bls20AWS** [comment]
Please add all meta information in an "example-workflow.json" file, this is documented in the _workflow_model

**Comment by fanhongy** [comment]
`example-workflow.json` files added. Thank you!

**Comment by bls20AWS** [comment]
looks good, thanks
