### ISSUE TITLE
New workflow submission: Add workflow for Textract StartDocumentDetection callback cdk example

### ISSUE THREAD

**Issue by dariusjs** [aws-samples/step-functions-workflows-collection#15]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

1. Use the model template located at https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow-mode to set up a README, template and any associated code.

2. All the information below must be provided in the "example-workflow.json" file cloned from the [model](https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow-model) **

Note the following information for the model:

- Description (intro.text) should be a 300-500 word explanation of how the pattern works.
- Simplicity: 3
- Diagram: ![image](https://raw.githubusercontent.com/dariusjs/step-functions-workflows-collection/feature-textract-callback-cdk/sfn-textract-callback-ts-cdk/resources/statemachine.png)
- Type: Standard
- Resources: https://aws.amazon.com/blogs/machine-learning/translating-scanned-pdf-documents-using-amazon-translate-and-amazon-textract/
- Framework: CDK
-  https://twitter.com/dariusjs

You must ensure that the sections of the model README.md are completed in full.

**Comment by bls20AWS** [comment]
Thanks for this great contribution @dariusjs. i have published it. If you are able to contribute more workflows, next time would you mind adding the workflow studio image (the one that shows the Service integrations).  Thank-you!
