### ISSUE TITLE
New workflow submission - SageMaker Pipeline Notifications workflow using CDK with Python

### ISSUE THREAD

**Issue by adrianjhunter** [aws-samples/step-functions-workflows-collection#155]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

Note the following information for the workflow:

- Name: SageMaker Pipeline Notifications
- Description: For customers with many running pipelines, it becomes challenging to see which ones may have failed. This workflow provides an alert of a failed pipeline execution for further investigation as to why the pipeline failed. The system sends an email notification via Amazon SNS.
- Simplicity: 3 - Application
- Diagram: Included
- Type: Standard
- Resources should link to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: CDK
- Language: Python
- PR: #154
- Author: [Adrian Hunter](https://www.linkedin.com/in/adrianhunter/)

You must ensure that the sections of the model README.md are completed in full.

**Comment by bls20AWS** [comment]
merged
