### ISSUE TITLE
Amazon Athena result processing

### ISSUE THREAD

**Issue by cremich** [aws-samples/step-functions-workflows-collection#16]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

1. Use the model template located at https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow-mode to set up a README, template and any associated code.

2. All the information below must be provided in the "example-workflow.json" file cloned from the [model](https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow-model) **

Note the following information for the model:

### Description
This workflow demonstrates how to ue AWS Step Functions to process results from Amazon Athena Queries written to Amazon S3.

When running SQL queries using Amazon Athena, the query results can be stored in specified locations. One potential location is Amazon S3 to view and download the query result sets for different postprocessing use cases. Amazon Athena automatically stores query results and metadata information for each query that runs in a query result location that you can specify in Amazon S3. If necessary, you can access the files in this location to work with them. You can also download query result files directly from the Amazon Athena console.

Typical use cases where this pattern is helpful, are
- querying [cost and usage reports](https://wellarchitectedlabs.com/cost/300_labs/300_automated_cur_query_and_email_delivery/) and send the results via E-Mail (or other channels) to development or operation teams.
- querying [engagement analytics](https://github.com/aws-samples/communication-developer-services-reference-architectures#federated-segmentation-with-amazon-athena) data, create a pre-signed URL and send this to marketing department members to download the results.
- querying [cloud trail logs](https://docs.aws.amazon.com/athena/latest/ug/cloudtrail-logs.html) and send the results to your security team for forensic or auditing purposes.

### Simplicity
1

### Diagram
![stepfunctions_graph](https://user-images.githubusercontent.com/5345186/180433631-8da07c9b-5697-45c5-bacd-7c4ec36fd1d5.png)

### Type:
Standard

### Resources should link to AWS documentation and AWS blogs related to the post (1-5 maximum)
* https://wellarchitectedlabs.com/cost/300_labs/300_automated_cur_query_and_email_delivery/
* https://github.com/aws-samples/communication-developer-services-reference-architectures#federated-segmentation-with-amazon-athena
* https://docs.aws.amazon.com/athena/latest/ug/cloudtrail-logs.html

### Framework
AWS SAM

### Author bio:
Hi my name is Christian. I am working as an AWS Solution Architect at DFL Digital Sports GmbH. Based in cologne with my beloved wife and two kids. I am interested in all things around ☁️ (cloud), 👨‍💻 (tech) and 🧠 (AI/ML).

With 10+ years of experience in several roles, I have a lot to talk about and love to share my experiences. I worked as a software developer in several companies in the media and entertainment business, as well as a solution engineer in a consulting company. 

I love those challenges to provide high scalable systems for millions of users. And I love to collaborate with lots of people to design systems in front of a whiteboard.

I use AWS since 2013 where we built a voting system for a big live TV show in germany. Since then I became a big fan on cloud, AWS and domain driven design.

Linkedin: https://www.linkedin.com/in/christian-bonzelet/
Github: https://www.github.com/cremich
Twitter: https://www.twitter.com/cremich

You must ensure that the sections of the model README.md are completed in full.

**Comment by bls20AWS** [comment]
Thanks for contributing, this has now been added to thr collection.
