### ISSUE TITLE
 New workflow submission - Dynamically process data with a Map state CDK

### ISSUE THREAD

**Issue by Yulan-coder** [aws-samples/step-functions-workflows-collection#179]
Note the following information for the model:
Name: dynamically-process-data-with-map-state-cdk
Description: This workflow demonstrates dynamic parallelism using a Map state.
Simplicity: 1 - Fundamental
Language: Typescript
Diagram: Included in the PR
PR: #178 
Type: Standard
Framework: CDK
Author: Zainab Allawi

**Comment by bls20AWS** [comment]
merged
