### ISSUE TITLE
Script Generator

### ISSUE THREAD

**Issue by ottl-seo** [aws-samples/step-functions-workflows-collection#18]
# "Script Generator" Application

1. Use the model template located at https://github.com/ottl-seo/step-functions-workflows-collection/tree/script-generator/script-generator to set up a README, template and any associated code.

2. All the information is below and in the "example-workflow.json" file

- Description: 
In this application, you can generate Script file in Video file. When you upload video file to S3 bucket, state machine will start processing video to text. The script content is extracted from the video and stored as script.txt in S3.

- Simplicity: `3 - Application`
- Type: `Standard`
- Resources 
  - [Amazon Transcribe document](https://docs.aws.amazon.com/ko_kr/transcribe/latest/APIReference/API_StartTranscriptionJob.html)
  - [AWS Step Functions Workshop](https://catalog.us-east-1.prod.workshops.aws/workshops/9e0368c0-8c49-4bec-a210-8480b51a34ac/en-US/introduction)
  - 

- Framework: `SAM`

### Diagram:  
![stepfunctions_graph](https://user-images.githubusercontent.com/61778930/180662056-1b11801b-60ff-4c9b-a9b5-e3c3e4131ddb.png)

### Author bio: 

|![yoonseokim](https://user-images.githubusercontent.com/61778930/180662205-3fc137bc-a7c7-4d7d-81e5-541f18676346.jpeg)|[Yoonseo Kim](https://www.linkedin.com/in/yoonseo-kim-573780208/), Solutions Architect in Amazon Web Service Korea|
|:---:|:---:|

**Comment by bls20AWS** [comment]
Thanks for this awesome workflow! it's now been published to the collection.
