### ISSUE TITLE
 New workflow submission - Start a Workflow within a Workflow

### ISSUE THREAD

**Issue by Yulan-coder** [aws-samples/step-functions-workflows-collection#182]
Note the following information for the model:      
Name: workflow-within-a-workflow   
Description: This sample project demonstrates how to use an AWS Step Functions state machine to launch other state machine executions. The state machine combines workflows using a Step Functions StartExecution task state with various integration patterns.
Simplicity: 1 - Fundamental     
Language: Javascript     
Diagram: Included in the PR.     
PR: #181 
Type: Standard 
Framework: SAM 
Author: Zainab Allawi

**Comment by bls20AWS** [comment]
merged
