### ISSUE TITLE
New Workflow Submission - Start a Workflow within a Workflow CDK

### ISSUE THREAD

**Issue by Yulan-coder** [aws-samples/step-functions-workflows-collection#184]
Note the following information for the model:
Name: workflow-within-a-workflow-cdk
Description: This sample project demonstrates how to use an AWS Step Functions state machine to launch other state machine executions. The state machine combines workflows using a Step Functions StartExecution task state with various integration patterns.
Simplicity: 1 - Fundamental
Language: Typescript
Diagram: Included in the PR.
PR: #182 
Type: Standard
Framework: CDK
Author: Zainab Allawi

**Comment by bls20AWS** [comment]
merged
