### ISSUE TITLE
New workflow submission - Transfer Data Records (Lambda, DynamoDB, Amazon SQS) - SAM

### ISSUE THREAD

**Issue by mosalahs** [aws-samples/step-functions-workflows-collection#190]
Note the following information for the model:
Name: Transfer Data Records (Lambda, DynamoDB, Amazon SQS)
Description: This sample project demonstrates how to read values from an Amazon DynamoDB table and send them to Amazon SQS using AWS Step Functions. Deploying this sample project will create a Step Functions state machine, a DynamoDB table, an AWS Lambda function, and an Amazon SQS topic.
Simplicity: 1 - Fundamental
Language: Javascript
Diagram: Included in the PR.
PR: #196 
Type: Standard
Framework: SAM
Author: Mohamed Salah

**Comment by bls20AWS** [comment]
hello, i dont see a PR for this

**Comment by bls20AWS** [comment]
merged
