### ISSUE TITLE
[New Workflow Submission] - lookout-for-vision-inference-sam

### ISSUE THREAD

**Issue by sawchengling66** [aws-samples/step-functions-workflows-collection#193]
Note the following information for the model:

Name: distributed-map-montecarlo
Description: This workflow demonstrates how to use Step Functions to orchestrate detection of anomalies in image uploaded into Amazon S3 bucket with Amazon Lookout for Vision. 
Simplicity: 3 - Application
Diagram: Included
Type: Standard
Framework: SAM
Language: Python
PR: https://github.com/aws-samples/step-functions-workflows-collection/pull/192
Author: [Cheng Ling Saw](https://www.linkedin.com/in/saw-cheng-ling/)

**Comment by bls20AWS** [comment]
merged
