### ISSUE TITLE
[New workflow submission] - Image Processing App 

### ISSUE THREAD

**Issue by deepaksrinivasan27** [aws-samples/step-functions-workflows-collection#194]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

1. Use the model template located at https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model to set up a README, template and any associated code.

2. All the information below must be provided in the "example-workflow.json" file cloned from the [model](https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model) **

Note the following information for the model:

- Description: 
In today's digital age, cheque images are often used for financial transactions, and it's essential to have an efficient way to retrieve, merge, and archive them. In this post, we'll explore how to automate these processes using AWS Step Functions, a powerful tool for building serverless workflows.
We'll start by creating an S3 bucket and writing an entry into Dynamo DB Table with the state execution ID. This will enable us to keep track of the workflow and with the respective users.
Next, we'll use Lambda functions to make external web service calls to retrieve cheque IDs and corresponding cheque images. With this information, we'll merge the front and back images for each cheque ID and store them in the designated S3 bucket. We'll use a Map State in Step functions to enable parallel processing for multiple cheque IDs, making the workflow more efficient.
Finally, we'll create a zip file containing all the cheque images for easy archiving and sharing. This will be triggered by a final Lambda function, which completes the workflow.
We are creating a convenient process by automating the retrieval, merging, and archiving of cheque images using AWS Step Functions. This can save time and reduce errors, making it an ideal solution for businesses that deal with images regularly. The power of AWS Step Functions enables us to build serverless workflows that are scalable, reliable, and cost-effective.

- Simplicity: 3 - Application
- Diagram: Attached below
- Type: Standard
- Resources: 
> **AWS Step Functions** https://docs.aws.amazon.com/step-functions/latest/dg/welcome.html
> **Map state processing modes** https://docs.aws.amazon.com/step-functions/latest/dg/concepts-map-process-modes.html
> **AWS CDK** https://docs.aws.amazon.com/cdk/v2/guide/home.html

- Framework: CDK
- Author bio -  https://www.linkedin.com/in/deepaksrinivasan27/
- Deepak Srinivasan is a Cloud Application Architect with AWS Professional Services. He offers a wealth of expertise in assisting customers with their cloud infrastructure needs, including application optimization and serverless solutions. 

You must ensure that the sections of the model README.md are completed in full. - Attached below
![ImageProcessing-Workflow](https://user-images.githubusercontent.com/69312645/234428645-c736bb56-4e31-412e-98ce-990f49b41d8d.PNG)

_____________________________________________________________________

[README.md](https://github.com/aws-samples/step-functions-workflows-collection/files/11327516/README.md)

**Comment by bls20AWS** [comment]
Please create. PR for this. Use the model template located at https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model folder model to see how to lay out your folder.

**Comment by deepaksrinivasan27** [comment]
Linked the PR here.... https://github.com/aws-samples/step-functions-workflows-collection/pull/204

**Comment by bls20AWS** [comment]
Merged

**Comment by deepaksrinivasan27** [comment]
In today's digital age, cheque images are often used for financial transactions, and it's essential to have an efficient way to retrieve, merge, and archive them. In this post, we'll explore how to automate these processes using AWS Step Functions, a powerful tool for building serverless workflows.
We'll start by creating an S3 bucket and writing an entry into Dynamo DB Table with the state execution ID. This will enable us to keep track of the workflow and with the respective users.
Next, we'll use Lambda functions to make external web service calls to retrieve cheque IDs and corresponding cheque images. With this information, we'll merge the front and back images for each cheque ID and store them in the designated S3 bucket. We'll use a Map State in Step functions to enable parallel processing for multiple cheque IDs, making the workflow more efficient.
Finally, we'll create a zip file containing all the cheque images for easy archiving and sharing. This will be triggered by a final Lambda function, which completes the workflow.
We are creating a convenient process by automating the retrieval, merging, and archiving of cheque images using AWS Step Functions. This can save time and reduce errors, making it an ideal solution for businesses that deal with images regularly. The power of AWS Step Functions enables us to build serverless workflows that are scalable, reliable, and cost-effective.

**Comment by deepaksrinivasan27** [comment]
Profile Image Link: 
https://media.licdn.com/dms/image/C4D03AQEvDFENeM8CsQ/profile-displayphoto-shrink_800_800/0/1640723593591?e=1691020800&v=beta&t=HAvIK76gEdYowF-XxvTkqlOmad_uhkY9L7p1V56UZeQ

**Comment by deepaksrinivasan27** [comment]
Services Used:
S3, StepFunctions, Lambda
