### ISSUE TITLE
New workflow submission - Call a microservice with API Gateway - SAM

### ISSUE THREAD

**Issue by mosalahs** [aws-samples/step-functions-workflows-collection#197]
Note the following information for the model:
Name: Call a microservice running on Fargate using API Gateway integration
Description: This sample project demonstrates how to use Step Functions to make a call to API Gateway in order to interact with a service on AWS Fargate, and also to check whether the call succeeded.
Simplicity: 1 - Fundamental
Language: Javascript
Diagram: Included in the PR.
PR: 
Type: Standard
Framework: SAM
Author: Mohamed Salah

**Comment by bls20AWS** [comment]
Please create a PR for this. Use the model template located at https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model folder for reference
