### ISSUE TITLE
[Update] Script Generator 

### ISSUE THREAD

**Issue by ottl-seo** [aws-samples/step-functions-workflows-collection#20]
I wanna update workflow that I uploaded. (https://serverlessland.com/workflows/script-generator)
I just changed [example-workflow.json](https://github.com/ottl-seo/step-functions-workflows-collection/blob/script-generator/script-generator/example-workflow.json) file and [README](https://github.com/ottl-seo/step-functions-workflows-collection/blob/script-generator/script-generator/README.md) file.

Thanks!

**Comment by bls20AWS** [comment]
I noticed you closed this yourself? all is ok
