### ISSUE TITLE
Call a microservice running on Fargate using API Gateway integration

### ISSUE THREAD

**Issue by mosalahs** [aws-samples/step-functions-workflows-collection#200]
Note the following information for the model:
Name: Call a microservice running on Fargate using API Gateway integration
Description: This sample project demonstrates how to use Step Functions to make a call to API Gateway in order to interact with a service on AWS Fargate, and also to check whether the call succeeded.
Simplicity: 1 - Fundamental
Language: Javascript
Diagram: Included in the PR.
PR: #201
Type: Standard
Framework: SAM
Author: Mohamed Salah

**Comment by bls20AWS** [comment]
Please move the Step functions definition to a separate file, referencing in line on the template.yaml is not best practice

**Comment by bls20AWS** [comment]
closing due to lack of response
