### ISSUE TITLE
New workflow submission for Step Functions Task Timer with a task expiry date

### ISSUE THREAD

**Issue by sabornibhattacharya** [aws-samples/step-functions-workflows-collection#215]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

1. Use the model template located at https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model to set up a README, template and any associated code.

2. All the information below must be provided in the "example-workflow.json" file cloned from the [model](https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model) **

Note the following information for the model:

- Description: This workflow describes a scenario where an end user wants to complete few tasks that are user input dependent, within a timestamp.
- Simplicity: 3
- Diagram: This must link to an Exported PNG of the workflow that shows any service integrations, you can export this from Workflow studio.
- Type: Standard
- Resources should link to AWS documentation and AWS blogs related to the post (1-5 maximum).
   
- Framework: SAM
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio:
   I am Saborni Bhattacharya and I love making technical contents on my YouTube channel - https://www.youtube.com/channel/UCpYl6SiNRBfcZoi4EKqIwog. Here is my blog link as well - https://learnandexplorewithsab.blogspot.com/",
   linkedin: "https://www.linkedin.com/in/saborni-bhattacharya-5b523812a/

You must ensure that the sections of the model README.md are completed in full.

[PR](https://github.com/aws-samples/step-functions-workflows-collection/pull/214)

**Comment by bls20AWS** [comment]
merged
