### ISSUE TITLE
New Workflow to orchestrate a EMR Serverless job

### ISSUE THREAD

**Issue by andrea-lascola** [aws-samples/step-functions-workflows-collection#221]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

1. Use the model template located at https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model to set up a README, template and any associated code.

2. All the information below must be provided in the "example-workflow.json" file cloned from the [model](https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model) **

Note the following information for the model:

- Description: included in example-wokflow.json
- Simplicity: 1 - Fundamental
- Diagram: included in example-wokflow.json
- Type: Standard
- Framework: CDK
- Author bio: included in example-wokflow.json

You must ensure that the sections of the model README.md are completed in full.

[Pull Request](https://github.com/aws-samples/step-functions-workflows-collection/pull/220)

**Comment by bls20AWS** [comment]
metged
