### ISSUE TITLE
IoT Analytics Step Function with Callback  Pattern

### ISSUE THREAD

**Issue by dariusjs** [aws-samples/step-functions-workflows-collection#251]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

1. Use the model template located at https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model to set up a README, template and any associated code.

2. All the information below must be provided in the "example-workflow.json" file cloned from the [model](https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model) **

Note the following information for the model:

- Description (introBox.text) should be a 300-500 word explanation of how the pattern works.
- Simplicity: 3 - Application
- Diagram: This must link to an Exported PNG of the workflow that shows any service integrations, you can export this from Workflow studio.
- Type: Must be one of Standard
- Resources should link to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: CDK
- Author bio: Twitter @dariusjs - Technical Account Manager at AWS

You must ensure that the sections of the model README.md are completed in full.

**Comment by bls20AWS** [comment]
Please add the example-workflow.json file

**Comment by dariusjs** [comment]
Sorry for that @bls20AWS, it is added now

**Comment by bls20AWS** [comment]
you left in sam instructions for a CDK pattern :) no worries i fixed it, but its somthing to remember for next time, it'll help us to publish faster for you.
