### ISSUE TITLE
New workflow submission

### ISSUE THREAD

**Issue by vmmadathil** [aws-samples/step-functions-workflows-collection#265]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

1. Use the model template located at https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model to set up a README, template and any associated code.

2. All the information below must be provided in the "example-workflow.json" file cloned from the [model](https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model) **

Note the following information for the model:

- Description (introBox.text) should be a 300-500 word explanation of how the pattern works.: This AWS Step Functions workflow automates the process of intelligently cropping pictures of individuals. Its main purpose is to crop around a picture of a person, removing any unnecessary background and focusing solely on the person in the image. The workflow is triggered whenever an image is uploaded to an S3 bucket. Once triggered, the image is retrieved and sent to Amazon Rekognition, where the detect_labels function is utilized to identify the objects within the image. If the function returns a person label, the image is cropped accordingly and saved to another S3 bucket.
- Simplicity: must be 1 of (`1 - Fundamental`, `2 -  Pattern`, `3 - Application` ): 3 - Application
- Diagram: This must link to an Exported PNG of the workflow that shows any service integrations, you can export this from Workflow studio.
![serverlessland_diagram](https://github.com/aws-samples/step-functions-workflows-collection/assets/30362269/3e255792-22d5-4cb7-b484-ef4ebed9087a)

- Type: Must be one of (`Standard`, `Express`): Standard 
- Resources should link to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: currently, we support SAM or CDK. : CDK
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio. : Vi Nguyen - Associate Solutions Architect, AWS; Visakh Madathil - Associate Solutions Architect, AWS

You must ensure that the sections of the model README.md are completed in full.

**Comment by bls20AWS** [comment]
merged
