### ISSUE TITLE
[New Workflow Submission] TTS Converter

### ISSUE THREAD

**Issue by ottl-seo** [aws-samples/step-functions-workflows-collection#28]
1. Use the model template located at https://github.com/ottl-seo/step-functions-workflows-collection/tree/yoon/tts-converter to set up a README, template and any associated code.

2. All the information below must be provided in the "example-workflow.json" file cloned from the [model](https://github.com/ottl-seo/step-functions-workflows-collection/tree/yoon/tts-converter) **

Note the following information for the model:

- Simplicity: `3 - Application`
- Type: `Standard`
- Framework: `SAM` 

## Description
This workflow is for reading text file to voice using Amazon Polly.

## Diagram

![statemachine](https://user-images.githubusercontent.com/61778930/182423253-e7daa22a-0b28-4c73-bb2e-ac1c8dfb046d.png)

## Resources related to the post
1. [Amazon Polly document](https://docs.aws.amazon.com/polly/latest/dg/API_GetSpeechSynthesisTask.html)
2. [AWS Step Functions Workshop](https://catalog.us-east-1.prod.workshops.aws/workshops/9e0368c0-8c49-4bec-a210-8480b51a34ac/en-US/introduction)

## Author bio

|![yoonseokim](https://user-images.githubusercontent.com/61778930/180662205-3fc137bc-a7c7-4d7d-81e5-541f18676346.jpeg)|[Yoonseo Kim](https://www.linkedin.com/in/yoonseo-kim-573780208/), Solutions Architect in Amazon Web Service Korea|
|:---:|:---:|

**Comment by boyney123** [comment]
Thanks! All merged
