### ISSUE TITLE
New workflow submission for Checkout Processing System

### ISSUE THREAD

**Issue by pjx98** [aws-samples/step-functions-workflows-collection#285]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

1. Use the model template located at https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model to set up a README, template and any associated code.

2. All the information below must be provided in the "example-workflow.json" file cloned from the [model](https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model) **

Note the following information for the model:

- Description: The example implements a checkout processing workflow that simulates a series of steps that an order must go through before notifying the result to the user.

- Simplicity: 2 -  Pattern

- Diagram: /resources/workflow_diagram.png

- Type: Standard
- Resources should link to AWS documentation and AWS blogs related to the post (1-5 maximum).

- Framework: SAM

- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio: 
   Jing Xiang is a Solutions Architect at AWS based in Singapore. Linkedin: www.linkedin.com/in/jing-xiang-peh

You must ensure that the sections of the model README.md are completed in full.

[PR #284 ](https://github.com/aws-samples/step-functions-workflows-collection/pull/284)

**Comment by bls20AWS** [comment]
merged
