### ISSUE TITLE
New workflow submission for async-state-machine-streaming-lambda-results

### ISSUE THREAD

**Issue by rossboast** [aws-samples/step-functions-workflows-collection#288]
Note the following information for the model:

- Description:  This example pattern demonstrates how you can use a streaming Lambda, exposed over HTTP using a Function URL, to receive live updates from an asynchronous Express workflow. The workflow is triggered by a HTTP POST request to an API Gateway endpoint. This endpoint triggers an asynchronous execution of a Step Functions Express workflow and returns the ExecutionARN for the execution and a Lambda Function URL. The ExecutionARN can be supplied to the Lambda Function URL as a query parameter via a HTTP GET request to enable the client to receive streaming results in JSON Lines format as the asynchronous workflow progresses
- Simplicity: 2 -  Pattern
- Diagram: resources/statemachine.png and resources/architecture.png
- Type: Express
- Resources: links to three related SAM and Step Functions workshops.
- Framework: SAM
- Author bio: included.

You must ensure that the sections of the model README.md are completed in full.

PR #287

**Comment by bls20AWS** [comment]
merged, will go live within 24 hours
