### ISSUE TITLE
[New Workflow]: Parallel Human Approval Pattern

### ISSUE THREAD

**Issue by kasacis** [aws-samples/step-functions-workflows-collection#315]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

1. Use the model template located at https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model to set up a README, template and any associated code.

2. All the information below must be provided in the "example-workflow.json" file cloned from the [model](https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model) **

Note the following information for the model:

- Description: 
A new pattern has been developed for parallel human approval process for step functions.
There are some cases, in which approvals from multiple people are required to complete the whole process. In a parallel approval workflow, each person’s approval is individual and is required separately.

This pattern allows you to integrate parallel human approval process into your workflows. The task sends a message to three SNS topic which send a notification to a human reviewer or approver by email for example. The workflow then waits until the approver completes their review. Depending on the review outcome the workflow finishes.

- Simplicity: 2-Pattern
- Diagram: /resources/statemachine.png
- Type: Standard
- Framework: SAM
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.
https://www.linkedin.com/in/serdakasaci/

You must ensure that the sections of the model README.md are completed in full.

PR #314

**Comment by bls20AWS** [comment]
Merged, will go live within 24 hours
