### ISSUE TITLE
File Processing Workflow

### ISSUE THREAD

**Issue by soumik6082** [aws-samples/step-functions-workflows-collection#324]
Issue based on pull request https://github.com/aws-samples/step-functions-workflows-collection/pull/323

1. README [ ./eventbridge-stepfunction-lambda-python-cdk/README.md]

2. example-workflow.json [ ./eventbridge-stepfunction-lambda-python-cdk/file-processing-workflow-model/example-workflow.json]

IDEA collected from [https://quip-amazon.com/VqBUAHFgmKxv/Serverless-Workflows-Collection-Submission-Ideas under Level 2 Patterns as File Processing Workflow]

You must ensure that the sections of the model README.md are completed in full.

**Comment by bls20AWS** [comment]
The PR had 4,000 files, please review and resubmit
