### ISSUE TITLE
Invoke Amazon Bedrock Model from AWS Step Functions Workflow

### ISSUE THREAD

**Issue by kasacis** [aws-samples/step-functions-workflows-collection#327]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.

To learn more about submitting a workflow, read the publishing guidelines page.

1. Use the model template located at https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model to set up a README, template and any associated code.

2. All the information below must be provided in the "example-workflow.json" file cloned from the [model](https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model) **

Note the following information for the model:

- Description : see README.md
- Simplicity: 2
- Diagram: done
- Type: Standard
- Resources should link to AWS documentation and AWS blogs related to the post (1-5 maximum).
- Framework: SAM
- Author bio may include a LinkedIn and/or Twitter reference and a 1-sentence bio.

You must ensure that the sections of the model README.md are completed in full.

**Comment by kasacis** [comment]
PR: #328

**Comment by bls20AWS** [comment]
merged
