### ISSUE TITLE
[New Workflow Submission] Calling Asynchronous API with Callbacks

### ISSUE THREAD

**Issue by hosshoss** [aws-samples/step-functions-workflows-collection#331]
To submit a workflow to the Step Functions Workflows Collection, submit an issue with the following information.
To learn more about submitting a workflow, read the publishing guidelines page.
Use the model template located at https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model to set up a README, template and any associated code.
All the information below must be provided in the "example-workflow.json" file cloned from the [model](https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model) **
Note the following information for the model:

* Description (introBox.text) should be a 300-500 word explanation of how the pattern works.
* Simplicity: 2 - Pattern
* Diagram: provided 
* Type: Standard 
* Resources should link to AWS documentation and AWS blogs related to the post (1-5 maximum): provided example-workflow.json
* Framework: SAM 
* Author bio: provided in example-workflow.json

You must ensure that the sections of the model README.md are completed in full.

**Comment by bls20AWS** [comment]
merged
