### ISSUE TITLE
[New Workflow Submission] StepFunctions workflow that cleans up idle Realtime Sagemaker Inference Endpoints

### ISSUE THREAD

**Issue by dariusjs** [aws-samples/step-functions-workflows-collection#333]
This workflow demonstrates how StepFunctions can provide a low code mechanism to run automation maintenance activities on cleaning up idle Sagemaker Inference endpoints that are deployed with a specific AWS Tag. There is a sample python notebook supplied that deploys an endpoint how a  data scientist would normally deploy their work.

**Comment by bls20AWS** [comment]
merged
