### ISSUE TITLE
[New Workflow Submission] Common Error Handling Pattern

### ISSUE THREAD

**Issue by wagneraw** [aws-samples/step-functions-workflows-collection#335]
This pattern shows how to use a common error reporting task within a Step Function. People often want to use a single common error reporting task within their Step Function so that they don't have to duplicate the functionality across many different states. The challenge with this approach is that while that common error reporting task can get the error message from whatever state failed, it doesn't actually get the name of the state that failed. This is a challenge if you have two dozen different Lambda functions, and you're not sure which one caused the error. These example workflows work around this problem in two different ways.

**Comment by bls20AWS** [comment]
merged
