### ISSUE TITLE
[New Workflow Submission] Resource Configuration Backup Pattern

### ISSUE THREAD

**Issue by ShehryarAbbasi** [aws-samples/step-functions-workflows-collection#337]
This pattern allows for finding and storing Resource configurations in S3 for Resource Types supported by AWS Config. This low-code solution uses only AWS SDK integrations, as well as, an existing AWS Config Aggregator, in order to provide a centralized location to store Resource configurations from multi-region, multi-account, as point-in-time snapshots. These configuration snapshots are stored in S3 with a Date-Account-Region-ResourceType partitioning structure, which can then be referenced in situations such as auditing, disaster recovery, restoring older configurations, as well as for reviewing configurations for Resources which were created without using infrastructure-as-code.

**Comment by bls20AWS** [comment]
merged
