### ISSUE TITLE
Bug: Sample _workflow_model has a broken CLI command "missing directory"

### ISSUE THREAD

**Issue by hosshoss** [aws-samples/step-functions-workflows-collection#347]
The sample [_workflow_model](https://github.com/aws-samples/step-functions-workflows-collection/tree/main/_workflow_model) has incorrect directory in the CLI command mention in README.md

`cd _workflow-model` should be `cd step-functions-workflows-collection/_workflow-model`

**Comment by bls20AWS** [comment]
merged
