### ISSUE TITLE
Request for Fixing Serverlessland Error about Word Filtering Script Generator Application

### ISSUE THREAD

**Issue by ottl-seo** [aws-samples/step-functions-workflows-collection#47]
Hi, 
I uploaded an application in August, but I think there is an error in the CloudFormation template. 

There is no problem if I deploy it using [this file](https://github.com/aws-samples/step-functions-workflows-collection/blob/main/word-filtering-script-generator/template.yaml) that is uploaded in Github now, 
but there is a problem when I deploy the template by 'Launch Stack' button on [Serverlessland page](https://serverlessland.com/workflows/script-generator). 
### **Could you change the template of [ServerlessLand](https://serverlessland.com/workflows/script-generator) to [GitHub template file](https://github.com/aws-samples/step-functions-workflows-collection/blob/main/word-filtering-script-generator/template.yaml)?** 

Thank you.

**Comment by ottl-seo** [comment]
@boyney123 
Hi, I'm sorry for bothering you.
Can you help me fixing this issue?

**Comment by singledigit** [comment]
Serverlessland uses the file from GitHub. Can you create a PR with the change you want?
