### ISSUE TITLE
Extra space in cqrs/example-workflow.json file "simplicity" option causes Serverless Land Workflows creating two filter options for "2 - Pattern"

### ISSUE THREAD

**Issue by tolga-orhon** [aws-samples/step-functions-workflows-collection#60]
**Describe the bug**
There is an extra space in cqrs/example-workflow.json file that is causing Serverless Land Workflows options showing two filter options for "2 - Pattern"

**To Reproduce**
1. Go to 'https://serverlessland.com/workflows'
2. Check on the filter options under Level section

**Expected behavior**
There should be only one option for 2 - Pattern

Submitting a PR shortly to fix the issue

**Comment by bls20AWS** [comment]
good catch. thanks
